import { ColorPalette, GlobalProjectConfig, CanvasElement, BuilderSection } from '../../types/builder';

export const FONT_OPTIONS = [
  { label: 'Playfair Display (Serif Mewah)', value: 'Playfair Display, serif', category: 'serif' },
  { label: 'Cinzel (Serif Klasik / Royal)', value: 'Cinzel, serif', category: 'serif' },
  { label: 'Cormorant Garamond (Vintage Editorial)', value: 'Cormorant Garamond, serif', category: 'serif' },
  { label: 'Great Vibes (Kaligrafi Bersambung)', value: 'Great Vibes, cursive', category: 'script' },
  { label: 'Alex Brush (Kaligrafi Lembut)', value: 'Alex Brush, cursive', category: 'script' },
  { label: 'Dancing Script (Santai Romantis)', value: 'Dancing Script, cursive', category: 'script' },
  { label: 'Pinyon Script (Handwriting Mewah)', value: 'Pinyon Script, cursive', category: 'script' },
  { label: 'Amiri (Kaligrafi Arab Tradisional)', value: 'Amiri, serif', category: 'arabic' },
  { label: 'Montserrat (Modern Bersih)', value: 'Montserrat, sans-serif', category: 'sans' },
  { label: 'Plus Jakarta Sans (Elegan Modern)', value: 'Plus Jakarta Sans, sans-serif', category: 'sans' },
];

export const COLOR_PALETTES: ColorPalette[] = [
  {
    id: 'sage-botanical',
    name: 'Vintage Sage Botanical',
    primary: '#51583D',
    secondary: '#767D63',
    accent: '#C2A676',
    background: '#FAF9F5',
    card: '#FFFFFF',
    text: '#2C2B29',
  },
  {
    id: 'champagne-gold',
    name: 'Royal Champagne & Gold',
    primary: '#8C6A43',
    secondary: '#C5A059',
    accent: '#E8D8BA',
    background: '#FAF6F0',
    card: '#FFFFFF',
    text: '#3D312A',
  },
  {
    id: 'dusty-rose',
    name: 'Romantic Dusty Rose',
    primary: '#8A5D65',
    secondary: '#B88691',
    accent: '#D4AF37',
    background: '#FCF8F8',
    card: '#FFFFFF',
    text: '#3A2E30',
  },
  {
    id: 'midnight-navy',
    name: 'Midnight Navy & Gold',
    primary: '#1E293B',
    secondary: '#334155',
    accent: '#F59E0B',
    background: '#0F172A',
    card: '#1E293B',
    text: '#F8FAFC',
  },
  {
    id: 'terracotta-earth',
    name: 'Terracotta Earthy Warm',
    primary: '#9A5B42',
    secondary: '#C47B5D',
    accent: '#E3B778',
    background: '#FAF5F0',
    card: '#FFFFFF',
    text: '#382823',
  },
];

export const ORNAMENT_LIBRARY = [
  {
    name: 'Bunga Kiri Atas (Sage)',
    src: '/assets/flowers/eucalyptus-branch.svg',
    type: 'flower',
    width: 140,
    height: 140,
  },
  {
    name: 'Bunga Kanan Atas (Olive)',
    src: '/assets/leaves/olive-leaf.svg',
    type: 'flower',
    width: 140,
    height: 140,
  },
  {
    name: 'Bouquet Bunga Bawah',
    src: '/assets/flowers/blooming-bouquet.svg',
    type: 'flower',
    width: 220,
    height: 120,
  },
  {
    name: 'Kaligrafi Bismillah',
    src: '/assets/ornaments/bismillah-calligraphy.svg',
    type: 'bismillah',
    width: 200,
    height: 60,
  },
  {
    name: 'Wax Seal Gold Monogram',
    src: '/assets/ornaments/wax-seal-gold.svg',
    type: 'seal',
    width: 90,
    height: 90,
  },
  {
    name: 'Golden Frame Arch',
    src: '/assets/ornaments/golden-flourish.svg',
    type: 'ornament',
    width: 180,
    height: 50,
  },
  {
    name: 'Foto Pernikahan 01 (Assetku)',
    src: '/assets/user-uploads/WhatsApp Image 2026-10-06 at 06.35.03.jpeg',
    type: 'image',
    width: 200,
    height: 250,
  },
  {
    name: 'Foto Pernikahan 02 (Assetku)',
    src: '/assets/user-uploads/WhatsApp Image 2026-10-06 at 06.35.03 (1).jpeg',
    type: 'image',
    width: 200,
    height: 250,
  },
  {
    name: 'Foto Pernikahan 03 (Assetku)',
    src: '/assets/user-uploads/WhatsApp Image 2026-10-06 at 06.35.03 (2).jpeg',
    type: 'image',
    width: 200,
    height: 250,
  },
  {
    name: 'Foto Pernikahan 04 (Assetku)',
    src: '/assets/user-uploads/WhatsApp Image 2026-10-06 at 06.35.04.jpeg',
    type: 'image',
    width: 200,
    height: 250,
  },
  {
    name: 'Foto Pernikahan 05 (Assetku)',
    src: '/assets/user-uploads/WhatsApp Image 2026-10-06 at 06.35.04 (1).jpeg',
    type: 'image',
    width: 200,
    height: 250,
  },
];

export const SHAPE_PRESETS = [
  {
    name: 'Arch Frame (Lengkung Kubah)',
    shapeType: 'arch',
    width: 180,
    height: 240,
    borderRadius: 90,
    borderWidth: 2,
    borderColor: '#C2A676',
    backgroundColor: '#FFFFFF',
  },
  {
    name: 'Monogram Seal Lingkaran',
    shapeType: 'circle',
    width: 80,
    height: 80,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: '#C2A676',
    backgroundColor: '#51583D',
  },
  {
    name: 'Kartu Rounded Mewah',
    shapeType: 'rectangle',
    width: 320,
    height: 200,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#C2A676',
    backgroundColor: '#FFFFFF',
  },
  {
    name: 'Pill Badge (Label Kapsul)',
    shapeType: 'pill',
    width: 160,
    height: 38,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#C2A676',
    backgroundColor: '#FAF9F5',
  },
  {
    name: 'Garis Pembatas Emas (Divider)',
    shapeType: 'divider-line',
    width: 140,
    height: 2,
    borderRadius: 2,
    borderWidth: 0,
    borderColor: 'transparent',
    backgroundColor: '#C2A676',
  },
];

export const DEFAULT_INITIAL_PROJECT: GlobalProjectConfig = {
  id: 'nikahhub-custom-invitation',
  title: 'The Wedding of Dion & Sarah',
  groomName: 'Dion Permana',
  brideName: 'Sarah Maulida',
  eventDate: '2026-11-28',
  monogram: 'D & S',
  activePalette: 'sage-botanical',
  ambientEffect: 'petals',
  backgroundMusic: {
    enabled: true,
    title: 'A Thousand Years (Instrumental)',
    artist: 'Wedding Piano & Cello',
    url: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-wedding-piano-112191.mp3',
    autoPlay: true,
  },
  sections: [
    {
      id: 'section-cover',
      title: 'Cover / Opening Screen',
      type: 'cover',
      enabled: true,
      backgroundColor: '#FAF9F5',
      minHeight: 680,
      paddingY: 40,
      elements: [
        {
          id: 'el-cover-badge',
          name: 'Badge Undangan',
          type: 'text',
          sectionId: 'section-cover',
          content: 'WEDDING INVITATION',
          fontFamily: 'Montserrat, sans-serif',
          fontSize: 11,
          fontWeight: '600',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 4,
          lineHeight: 1.2,
          textColor: '#51583D',
          backgroundColor: '#51583D15',
          borderColor: '#C2A676',
          borderWidth: 1,
          borderStyle: 'solid',
          borderRadius: 999,
          width: 220,
          height: 32,
          x: 0,
          y: -220,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'sm',
          animation: { type: 'fadeDown', duration: 1.2, delay: 0.1, trigger: 'onLoad' },
        },
        {
          id: 'el-cover-seal',
          name: 'Wax Monogram Seal',
          type: 'shape',
          shapeType: 'circle',
          sectionId: 'section-cover',
          content: 'D & S',
          fontFamily: 'Cinzel, serif',
          fontSize: 22,
          fontWeight: '700',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 2,
          lineHeight: 1,
          textColor: '#E8D8BA',
          backgroundColor: '#51583D',
          borderColor: '#C2A676',
          borderWidth: 2,
          borderStyle: 'solid',
          borderRadius: 999,
          width: 80,
          height: 80,
          x: 0,
          y: -140,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'lg',
          animation: { type: 'zoomIn', duration: 1.2, delay: 0.2, trigger: 'onLoad' },
        },
        {
          id: 'el-cover-tagline',
          name: 'Tagline The Wedding of',
          type: 'text',
          sectionId: 'section-cover',
          content: 'The Wedding of',
          fontFamily: 'Cormorant Garamond, serif',
          fontSize: 15,
          fontWeight: '400',
          fontStyle: 'italic',
          textAlign: 'center',
          letterSpacing: 3,
          lineHeight: 1.2,
          textColor: '#767D63',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 260,
          height: 24,
          x: 0,
          y: -75,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeIn', duration: 1, delay: 0.3, trigger: 'onLoad' },
        },
        {
          id: 'el-cover-names',
          name: 'Nama Mempelai Cover',
          type: 'text',
          sectionId: 'section-cover',
          content: 'Dion & Sarah',
          fontFamily: 'Playfair Display, serif',
          fontSize: 34,
          fontWeight: '600',
          fontStyle: 'italic',
          textAlign: 'center',
          letterSpacing: 1,
          lineHeight: 1.15,
          textColor: '#2C2B29',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 320,
          height: 50,
          x: 0,
          y: -25,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeUp', duration: 1.3, delay: 0.4, trigger: 'onLoad' },
        },
        {
          id: 'el-cover-guest-box',
          name: 'Kotak Nama Tamu',
          type: 'shape',
          shapeType: 'rectangle',
          sectionId: 'section-cover',
          content: 'Kepada Yth:\nBapak/Ibu/Saudara/i\nTamu Undangan',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          fontSize: 12,
          fontWeight: '500',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 0.5,
          lineHeight: 1.5,
          textColor: '#444241',
          backgroundColor: '#FFFFFFEE',
          borderColor: '#C2A67688',
          borderWidth: 1,
          borderStyle: 'solid',
          borderRadius: 18,
          width: 280,
          height: 90,
          x: 0,
          y: 70,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'md',
          animation: { type: 'fadeUp', duration: 1.2, delay: 0.5, trigger: 'onLoad' },
        },
        {
          id: 'el-cover-open-btn',
          name: 'Tombol Buka Undangan',
          type: 'button',
          sectionId: 'section-cover',
          content: '💌 BUKA UNDANGAN',
          fontFamily: 'Montserrat, sans-serif',
          fontSize: 12,
          fontWeight: '700',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 2,
          lineHeight: 1,
          textColor: '#FAF9F5',
          backgroundColor: '#51583D',
          borderColor: '#C2A676',
          borderWidth: 1.5,
          borderStyle: 'solid',
          borderRadius: 999,
          width: 250,
          height: 48,
          x: 0,
          y: 170,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'lg',
          animation: { type: 'fadeUp', duration: 1.3, delay: 0.6, trigger: 'onLoad' },
        },
      ],
    },
    {
      id: 'section-ayat',
      title: 'Ayat Suci & Doa',
      type: 'ayat',
      enabled: true,
      backgroundColor: '#838A6D',
      minHeight: 520,
      paddingY: 45,
      elements: [
        {
          id: 'el-ayat-card',
          name: 'Kartu Ayat Hijau Arch',
          type: 'shape',
          shapeType: 'rectangle',
          sectionId: 'section-ayat',
          content: '',
          fontFamily: 'Amiri, serif',
          fontSize: 14,
          fontWeight: '400',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 0,
          lineHeight: 1.5,
          textColor: '#FAF9F5',
          backgroundColor: '#51583D88',
          borderColor: '#FAF9F544',
          borderWidth: 1,
          borderStyle: 'solid',
          borderRadius: 24,
          width: 320,
          height: 400,
          x: 0,
          y: 0,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 5,
          shadow: 'xl',
          animation: { type: 'fadeUp', duration: 1.5, delay: 0.2, trigger: 'onScroll' },
        },
        {
          id: 'el-ayat-bismillah',
          name: 'Kaligrafi Bismillah',
          type: 'text',
          sectionId: 'section-ayat',
          content: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
          fontFamily: 'Amiri, serif',
          fontSize: 24,
          fontWeight: '700',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 1,
          lineHeight: 1.4,
          textColor: '#E8D8BA',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 280,
          height: 40,
          x: 0,
          y: -140,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeUp', duration: 1.3, delay: 0.3, trigger: 'onScroll' },
        },
        {
          id: 'el-ayat-arabic',
          name: 'Teks Ayat Arab',
          type: 'text',
          sectionId: 'section-ayat',
          content: 'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً',
          fontFamily: 'Amiri, serif',
          fontSize: 16,
          fontWeight: '400',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 0.5,
          lineHeight: 1.8,
          textColor: '#FAF9F5',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 270,
          height: 90,
          x: 0,
          y: -50,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeUp', duration: 1.4, delay: 0.4, trigger: 'onScroll' },
        },
        {
          id: 'el-ayat-latin',
          name: 'Terjemahan Ayat',
          type: 'text',
          sectionId: 'section-ayat',
          content: '"Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan untukmu dari jenismu sendiri agar kamu merasa tenteram."',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          fontSize: 11,
          fontWeight: '300',
          fontStyle: 'italic',
          textAlign: 'center',
          letterSpacing: 0.2,
          lineHeight: 1.6,
          textColor: '#FAF9F5DD',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 260,
          height: 70,
          x: 0,
          y: 60,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeUp', duration: 1.4, delay: 0.5, trigger: 'onScroll' },
        },
        {
          id: 'el-ayat-source',
          name: 'Badge Sumber Surat',
          type: 'text',
          sectionId: 'section-ayat',
          content: 'QS. AR-RUM: 21',
          fontFamily: 'Cinzel, serif',
          fontSize: 10,
          fontWeight: '700',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 3,
          lineHeight: 1,
          textColor: '#E8D8BA',
          backgroundColor: '#FAF9F522',
          borderColor: '#E8D8BA66',
          borderWidth: 1,
          borderStyle: 'solid',
          borderRadius: 999,
          width: 150,
          height: 28,
          x: 0,
          y: 140,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'sm',
          animation: { type: 'zoomIn', duration: 1.2, delay: 0.6, trigger: 'onScroll' },
        },
      ],
    },
    {
      id: 'section-couple',
      title: 'Profil Mempelai',
      type: 'couple',
      enabled: true,
      backgroundColor: '#FAF9F5',
      minHeight: 650,
      paddingY: 45,
      elements: [
        {
          id: 'el-couple-sub',
          name: 'Subtitle Bride & Groom',
          type: 'text',
          sectionId: 'section-couple',
          content: 'BRIDE & GROOM',
          fontFamily: 'Cormorant Garamond, serif',
          fontSize: 13,
          fontWeight: '600',
          fontStyle: 'italic',
          textAlign: 'center',
          letterSpacing: 3,
          lineHeight: 1,
          textColor: '#767D63',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 220,
          height: 20,
          x: 0,
          y: -240,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeDown', duration: 1.2, delay: 0.1, trigger: 'onScroll' },
        },
        {
          id: 'el-couple-title',
          name: 'Judul Mempelai Bahagia',
          type: 'text',
          sectionId: 'section-couple',
          content: 'Mempelai Bahagia',
          fontFamily: 'Playfair Display, serif',
          fontSize: 28,
          fontWeight: '700',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 1,
          lineHeight: 1.2,
          textColor: '#2C2B29',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 300,
          height: 38,
          x: 0,
          y: -205,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeUp', duration: 1.3, delay: 0.2, trigger: 'onScroll' },
        },
        {
          id: 'el-groom-photo',
          name: 'Foto Mempelai Pria Arch',
          type: 'image',
          sectionId: 'section-couple',
          content: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop',
          fontFamily: 'Montserrat, sans-serif',
          fontSize: 12,
          fontWeight: '400',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 0,
          lineHeight: 1,
          textColor: '#000000',
          backgroundColor: '#FFFFFF',
          borderColor: '#C2A676',
          borderWidth: 2,
          borderStyle: 'solid',
          borderRadius: 80,
          width: 140,
          height: 190,
          x: 0,
          y: -75,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'lg',
          animation: { type: 'zoomIn', duration: 1.4, delay: 0.3, trigger: 'onScroll' },
        },
        {
          id: 'el-groom-name',
          name: 'Nama Lengkap Pria',
          type: 'text',
          sectionId: 'section-couple',
          content: 'Dion Permana, S.T.',
          fontFamily: 'Playfair Display, serif',
          fontSize: 22,
          fontWeight: '700',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 0.5,
          lineHeight: 1.2,
          textColor: '#2C2B29',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 280,
          height: 32,
          x: 0,
          y: 45,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeUp', duration: 1.3, delay: 0.4, trigger: 'onScroll' },
        },
        {
          id: 'el-groom-desc',
          name: 'Keluarga Pria',
          type: 'text',
          sectionId: 'section-couple',
          content: 'Putra pertama dari:\nBpk. Bambang Permana & Ibu Ratna Dewi',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          fontSize: 11,
          fontWeight: '400',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 0.2,
          lineHeight: 1.6,
          textColor: '#686561',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 280,
          height: 40,
          x: 0,
          y: 85,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeUp', duration: 1.3, delay: 0.5, trigger: 'onScroll' },
        },
        {
          id: 'el-groom-ig',
          name: 'Tombol IG Pria',
          type: 'button',
          sectionId: 'section-couple',
          content: '@dion.permana',
          fontFamily: 'Montserrat, sans-serif',
          fontSize: 11,
          fontWeight: '600',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 1,
          lineHeight: 1,
          textColor: '#51583D',
          backgroundColor: '#51583D15',
          borderColor: '#767D6344',
          borderWidth: 1,
          borderStyle: 'solid',
          borderRadius: 999,
          width: 160,
          height: 32,
          x: 0,
          y: 135,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'sm',
          animation: { type: 'fadeUp', duration: 1.2, delay: 0.6, trigger: 'onScroll' },
        },
      ],
    },
    {
      id: 'section-events',
      title: 'Rangkaian Acara',
      type: 'events',
      enabled: true,
      backgroundColor: '#EEF0E9',
      minHeight: 580,
      paddingY: 45,
      elements: [
        {
          id: 'el-events-header',
          name: 'Header Rangkaian Acara',
          type: 'text',
          sectionId: 'section-events',
          content: 'Rangkaian Acara',
          fontFamily: 'Playfair Display, serif',
          fontSize: 28,
          fontWeight: '700',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 1,
          lineHeight: 1.2,
          textColor: '#2C2B29',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 280,
          height: 38,
          x: 0,
          y: -210,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeDown', duration: 1.3, delay: 0.1, trigger: 'onScroll' },
        },
        {
          id: 'el-akad-card',
          name: 'Kartu Akad Nikah',
          type: 'shape',
          shapeType: 'rectangle',
          sectionId: 'section-events',
          content: 'AKAD NIKAH\nMinggu, 28 November 2026\n08.00 - 10.00 WIB\n\nMasjid Agung Al-Falah\nJl. Raya Kebun Raya No. 45',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          fontSize: 12,
          fontWeight: '500',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 0.3,
          lineHeight: 1.6,
          textColor: '#2C2B29',
          backgroundColor: '#FAF9F5',
          borderColor: '#C2A67677',
          borderWidth: 1,
          borderStyle: 'solid',
          borderRadius: 22,
          width: 300,
          height: 170,
          x: 0,
          y: -80,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'md',
          animation: { type: 'fadeUp', duration: 1.5, delay: 0.25, trigger: 'onScroll' },
        },
        {
          id: 'el-resepsi-card',
          name: 'Kartu Resepsi',
          type: 'shape',
          shapeType: 'rectangle',
          sectionId: 'section-events',
          content: 'RESEPSI PERNIKAHAN\nMinggu, 28 November 2026\n11.00 - 14.00 WIB\n\nBallroom The Heritage Garden\nJl. Merpati Indah No. 12',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          fontSize: 12,
          fontWeight: '500',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 0.3,
          lineHeight: 1.6,
          textColor: '#2C2B29',
          backgroundColor: '#FAF9F5',
          borderColor: '#C2A67677',
          borderWidth: 1,
          borderStyle: 'solid',
          borderRadius: 22,
          width: 300,
          height: 170,
          x: 0,
          y: 110,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'md',
          animation: { type: 'fadeUp', duration: 1.5, delay: 0.35, trigger: 'onScroll' },
        },
      ],
    },
    {
      id: 'section-closing',
      title: 'Penutup & Terima Kasih',
      type: 'closing',
      enabled: true,
      backgroundColor: '#FAF9F5',
      minHeight: 480,
      paddingY: 45,
      elements: [
        {
          id: 'el-closing-note',
          name: 'Ucapan Terima Kasih',
          type: 'text',
          sectionId: 'section-closing',
          content: 'Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir serta memberikan doa restu.',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          fontSize: 11,
          fontWeight: '300',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 0.2,
          lineHeight: 1.7,
          textColor: '#686561',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 290,
          height: 60,
          x: 0,
          y: -100,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeUp', duration: 1.4, delay: 0.2, trigger: 'onScroll' },
        },
        {
          id: 'el-closing-names',
          name: 'Nama Penutup',
          type: 'text',
          sectionId: 'section-closing',
          content: 'Dion & Sarah',
          fontFamily: 'Playfair Display, serif',
          fontSize: 32,
          fontWeight: '700',
          fontStyle: 'italic',
          textAlign: 'center',
          letterSpacing: 1,
          lineHeight: 1.2,
          textColor: '#2C2B29',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 280,
          height: 45,
          x: 0,
          y: -10,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeUp', duration: 1.5, delay: 0.35, trigger: 'onScroll' },
        },
        {
          id: 'el-closing-family',
          name: 'Keluarga Besar',
          type: 'text',
          sectionId: 'section-closing',
          content: 'Beserta Keluarga Besar Kedua Mempelai',
          fontFamily: 'Cormorant Garamond, serif',
          fontSize: 13,
          fontWeight: '500',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 1,
          lineHeight: 1,
          textColor: '#51583D',
          backgroundColor: 'transparent',
          borderColor: 'transparent',
          borderWidth: 0,
          borderStyle: 'none',
          borderRadius: 0,
          width: 280,
          height: 25,
          x: 0,
          y: 35,
          rotation: 0,
          scale: 1,
          opacity: 1,
          zIndex: 10,
          shadow: 'none',
          animation: { type: 'fadeUp', duration: 1.3, delay: 0.45, trigger: 'onScroll' },
        },
      ],
    },
  ],
};
